#%RAML 1.0 DataType


type: object
displayName: address
properties: 
  'type ': 
    type: string
    required: true
  number: 
    type: any
    required: true
  street: 
    type: string
    required: true
  Unit: 
    type: string
    required: true
  City: 
    type: string
    required: true 
  State: 
    type: string
    required: true  
  zipcode: 
    type: string
    required: true 
  
     